language: ruby
bundler_args: "--without development"
rvm:
- 2.1.1
env:
  matrix:
  - SECRET_KEY_BASE=bolao2014-test-key APP_NAME=bolao2014-test EMAIL_FROM=notifications@bolao2014.test
  global:
    secure: EcvkSEnMUNDfK6HuMzHMZ0/AlCShhGfLjms1OQ5YZ10EjFwNRbBMDkC/D+gj4Jfv34qSp6k2IwPXskYZlQwCAEaZexOply+iO6NPu9E9FycOWcbmANhQNsFj0BJG1ZBEG7vdAjebc3ETbEICdT9iFYC+B38PXAa8xGQOMd1PVWc=
script:
- RAILS_ENV=test bundle exec rake --trace db:schema:load
- RAILS_ENV=test bundle exec rake --trace spec
before_script:
- psql -c 'create database bolao2014_test;' -U postgres
