language: ruby
bundler_args: "--without development"
rvm:
  - 2.1.1
#  - 2.1.2 # debugger gem can not be installed in 2.1.2 yet :(
env:
  matrix:
    - SECRET_KEY_BASE=bolao2014-test-key APP_NAME=bolao2014-test APP_SHORT_NAME=bolao-test APP_HOST=test.host APP_ADMIN_EMAIL=admin@bolao2014.test APP_CONTACT_EMAIL=contact@bolao2014.test EMAIL_FROM=notifications@bolao2014.test REDIS_URL='redis://localhost:6379'
  global:
    - secure: Dcv/or2/X/CwklcJIXvsQt17UkU5O2C39iBn/qsSkyHzynIheUvkz9SzRZy5yX+Uyz+h+QrCJ6F1G+yqen7xOo3AnkUUlrFqwBXzNbIEVPveg7T8XVrMOhP6LhKt+W2lBjlOmrqXulY6CgVDE3RsGCJs6dcHN34j6qUVCRiboqE=
script:
  - RAILS_ENV=test bundle exec rake --trace db:schema:load
  - RAILS_ENV=test bundle exec rake --trace spec
before_script:
  - psql -c 'create database bolao2014_test;' -U postgres
services:
  - redis-server
addons:
  postgresql: "9.3"
